#!/bin/bash

echo "🔧 Google OAuth Configuration Guide for SkillBridge"
echo "================================================="
echo ""
echo "📋 Current Configuration:"
echo "   Client ID: 694389954977-6m3ksdmkph01bmn98skfuac3mrvhaumu.apps.googleusercontent.com"
echo "   Current App URL: http://localhost:5175"
echo ""
echo "🌐 Steps to Fix OAuth Error:"
echo ""
echo "1. Go to Google Cloud Console: https://console.cloud.google.com/"
echo "2. Navigate to: APIs & Services → Credentials"
echo "3. Find your OAuth 2.0 client ID and click Edit (pencil icon)"
echo "4. In 'Authorized JavaScript origins' section, add these URLs:"
echo "   ✓ http://localhost:5173"
echo "   ✓ http://localhost:5174"
echo "   ✓ http://localhost:5175"
echo "   ✓ http://localhost:5176"
echo "   ✓ http://localhost:3000"
echo ""
echo "5. Click 'Save' and wait 2-3 minutes for changes to propagate"
echo ""
echo "🚀 Your app is currently running on: http://localhost:5175"
echo "🔙 Backend API is running on: http://localhost:8080"
echo ""
echo "💡 Tip: After making changes in Google Console, refresh your browser!"
